language: python
python:
    - "2.7"
before_install:
    - "export DISPLAY=:99"
    - "sh -e /etc/init.d/xvfb start"
install:
    - "pip install -e git://github.com/edx/xblock-sdk.git#egg=xblock-sdk"
    - "pip install -r $VIRTUAL_ENV/src/xblock-sdk/requirements.txt"
    - "pip install -r $VIRTUAL_ENV/src/xblock-sdk/test-requirements.txt"
    - "python setup.py develop"
script: pep8 leaderboards --max-line-length=120 && pylint leaderboards && python run_tests.py --with-coverage --cover-package=leaderboards
notifications:
  email: false
